name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ftp://your-ftp-server.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./tienda
        server-dir: /public_html/tienda
